Server:
  Mode: debug # debug | release
  Port: :8080
  DbType: "mysql"
  DbAutoMigrate: true # 是否自动迁移数据库表结构 (表结构没变可以不迁移, 提高启动速度)
  DbLogMode: "error" # 日志级别 silent, error, warn, info, 默认 info
  StartTime: "2024-01-01"
  MachineID: 1
Mysql:
  Host: "127.0.0.1"
  Port: "3306"
  Dbname: "gvb"
  Username: "root"
  Password: "liuman.."
Redis:
  DB: 7
  Addr: "127.0.0.1:6379"
  Password: ""
Log:
  Level: "debug" # debug | info | warn | error
  Format: "text" # text | json
  Directory: "log"
  DebugFileName: "./logs/debug/debug.log"
  InfoFileName: "./logs/info/info.log"
  WarnFileName: "./logs/warn/warn.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3
Session:
  Name: "mysession"
  Salt: "salt"
  MaxAge: 600 # second
JWT:
  Secret: "Clearmann"
  Expire: 24 # hour
  Issuer: "gvb"